# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2019-07-21 06:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pechati', '0004_osnastka_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='Klishe',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('available', models.BooleanField(default=True)),
                ('image', models.ImageField(blank=True, upload_to='klishe_image/')),
                ('form', models.CharField(choices=[('ip', 'ИП'), ('organisation', 'Организация')], default='ip', max_length=50)),
            ],
        ),
    ]
